### ISSUE TITLE
Ensure the ternary sniff is compatible with the Null Coalesce Operator ( ?? ) in PHP7

### ISSUE THREAD

**Issue by ingluisjimenez** [behance/php-sniffs#174]
As we are moving to PHP7 soon (at least in Pf), the null coalescing operator (??) has been added as syntactic sugar for the common case of needing to use a ternary in conjunction with isset().

Let's make sure the current sniffs for ternaries are compatible with this new operator.

**Comment by andyroo2000** [comment]
Use of `??` shouldn't have any effect on the ternary sniff.

The ternary sniff looks for the `T_INLINE_THEN` token.

Fortunately, PHPCS now supports `??` as a different token type: `T_COALESCE`.

https://pear.php.net/reference/PHP_CodeSniffer-latest/PHP_CodeSniffer/PHP_CodeSniffer_Tokens.html
